### PR TITLE
add custom type hint

### PR DESCRIPTION
**Pull request by MarceloSantosCorrea**
If there is another way, I apologize for this PR, but this contribution is to be able to add Model as type hint:
file `auto-route.php`
```
'patterns'     => [
    'slug'     => '([\w\-_]+)',
    'uuid'     => '([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})',
    'date'     => '([0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]))',
    "customer" => "App\Models\Customer",
],
```
Captura de Tela 2021-05-23 às 12 54 34

in controller

```
public function getShow(Customer $customer){}
```

### CODE REVIEW

**Comment by izniburak** [comment]
Hi @MarceloSantosCorrea ,
This is great! We will be able to add `model binding` functionality for Route parameters thanks to this PR.
Thank you so much for your effort! 💯 

I also have a suggestion about that:
We have to define a pattern for `Model` parameters right now. But actually, we shouldn't need to do this. I think we should handle all parameters related with any class that extends from `Model`. According to this, we can change your codes like that:

```php 
if ($typeHint !== null && class_exists($typeHint)) {
    if (!in_array($typeHint, ['int', 'float', 'string', 'bool']) && !in_array($typeHint, $patterns) 
        && !is_subclass_of($typeHint, 'Illuminate\Database\Eloquent\Model')) {
            continue;
    }
}
```

What do you think about that?

**Comment by MarceloSantosCorrea** [comment]
I thought about that too, but I wanted to make it broader in case you want to inject other types of classes, by injecting Laravel's dependencies.

**Comment by izniburak** [comment]
When do we use other types of classes for the Route params? As far as I know, for the Route params can be Model or primitives types like int, string, etc. What could we use else?

**Comment by MarceloSantosCorrea** [comment]
[Laravel](https://laravel.com/docs/8.x/container#zero-configuration-resolution), here is an example.

Another example that can be passed are Interfaces that can be solved with Binding

**Comment by izniburak** [comment]
I know that, but question is can we use Route param binding for all classes/interfaces types? According to documentation of the Laravel Routing, we can solve Model binding because Routing package supports that. But I couldn't find anything else for specific class binding in Router. You can check [this documentation.](https://laravel.com/docs/8.x/routing#route-model-binding)

Could you please share any example for any other class like Service, Library, Helper for solving Route param binding? I'm trying to sure about that.

**Comment by MarceloSantosCorrea** [comment]
'can we use route parameter binding for all types of classes/interfaces?', yes, I already made use of it, in the example I used was to implement the Socialite package, where I pass the network name by string parameter and in the controller it is returned to provider instance.

in routes/web.php
```
Route::get('login-social/{network}', [\App\Http\Controllers\LoginSocialController::class, 'login']);
```

in controller
```
class LoginSocialController extends Controller
{
    public function login(LoginSocialInterface $network)
    {
        return redirect($network->redirect());
    }
}
```

in App\Providers\AppServiceProvider
```
public function register()
{
    $this->app->singleton(LoginSocialInterface::class, function (\Illuminate\Foundation\Application $app) {
        $network = $app->router->current()->parameter('network');

        return \Socialite::driver($network);
    });
}
```

**Comment by izniburak** [comment]
Okay, I understand clearly. So, we can merge the your PR! 
Maybe later we can add Model binding support automatically not need to add any pattern. But now, these changes will be great for Auto-Router.

Thank you so much again!

**Pull request merged**
